### ISSUE TITLE
Should we highlight the current verse in the TPane?

### ISSUE THREAD

**Issue by lancelebanoff** [WycliffeAssociates/8woc#254]
If the current verse is highlighted in the TPane, it would help the user see exactly what they're checking.

**Comment by EvanWiederspan** [comment]
The verse also appears below in a separate box so they can easily see what theyre checking, i dont think highlighting it in the TPane is necessary. Or at least I don't think we should work on it with what little time we have left

**Comment by lancelebanoff** [comment]
Too late, I did it before looking at your comment, haha.
