### ISSUE TITLE
Disable SideNavMenu functionality during the tutorial.

### ISSUE THREAD

**Issue by EllDoubleYew** [WycliffeAssociates/8woc#273]
As someone learning how to use TC I do not want the tutorial to interfere with my workflow after I am finished with it so that I can being checking as quickly as possible.

Technical details: If you click on any item in the menu during the tutorial, the modal is queued for render as soon as it is able to after the tutorial. I just need to suppress those on

**Comment by EvanWiederspan** [comment]
the branch ew-disable-menubar adds this fucntionality
