### ISSUE TITLE
TPane.tc causes opening to fail

### ISSUE THREAD

**Issue by EvanWiederspan** [WycliffeAssociates/8woc#323]
The very existence of TPane.tc in the checkData folder causes the app to silently fail at the loading screen when re opening a project.

**Comment by EvanWiederspan** [comment]
I was working on the greek definition tool, and stored some data in the "TPane" namespace. For some reason, this causes the app to hang forever at the loading screen. I thought I may have accidentally messed with some code I wasn't supposed, but from what I can tell, it is literally just the existence of the TPane.tc that causes this. Putting any data in the TPane namespace at all, even if it is nonsense that is never used, causes this problem. I am hoping somebody more familiar with the project opening code can help me out with this problem.

Steps to reproduce:
Literally put any data in the "TPane" namespace anywhere in the code, then try to reopen an old project. Starting on the develop branch, I put the following line in TPane fetch data function:
api.putDataInCheckStore("TPane", "stuff", 2)
This is the only change I did to develop, and it made it so that I could not reopen a project
When I deleted the TPane.tc file in the project's checkData folder, I was able to open a project again

To me this signifies a serious problem with our project opener, and could be a major headache for future devleopers

Somebody more familiar with the project opener please help, because I have no idea why this is happening

**Comment by ihoegen** [comment]
I can look into it later today, but it might be solved by not having a tpane check store. Maybe apps be predefined as having save files, and if they are not defined, they don't generate a .TC file. This could be done in the manifest for the module.

**Comment by therealsamf** [comment]
Actually I think I know what the issue is: If TPane has data in its checkstore, then zero fetch datas need to be run and the core action that signifies for the loading screen to go away never gets called. I'll fix and pull request today. This is my theory anyway, I'll try to fix it and test

**Comment by ihoegen** [comment]
@therealsamf Try your fix on ew-greek-stuff and from there, a pull request could be made.

**Comment by therealsamf** [comment]
Pull request opened that fixes the problem that I theorized could be happening, if that doesn't work then lmk and I'll hop on ew-greek-stuff and dig deeper

**Comment by ihoegen** [comment]
I'll do a local merge tonight and poke around it.

**Comment by EvanWiederspan** [comment]
Im gonna close this, our pull request should have fixed it
